var GAME_LEVELS = [
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                                                               ",
   "x  xxxxx     xxxxx   xx   x xxxxxxx   xxxxx   xxxxx xxxxx                       ",
   "x  x    x   x     x  x    x    x      x    x    x   x                           ",
   "x                       x x    x      x     x   x   xxxx                        ",
   "x    y  x   x     x  x   xx    x      x    x    x   x                           ",
   "x  xxxxx     xxxxx   x    x    x      xxxxx   xxxxx xxxxx                       ",
   "x x                                                                             ",
   "x                                   y y                                         ",
   "x                                                                               ",
   "x                                   xxxx                                        ",
   "xx                           xxx                                                ",
   "x                        xxx              y y                                   ",
   "x                   xxx                                                         ",
   "xx                                            xxxx                              ",
   " xx           xx xx                              x                           x  ",
   "  xx @     y xx===xx  y                         yx               xxxxx   y   x  ",
   "   xxxxxxxxxxx!!!!!xxxxxxxxxx          xxxxxxxxxxxxxxx     xxxxxxx===xxxxxxxx===",
   "             xxxxxxx        xxx=======xx             x     x!!!!!!!!!!!!!!!!!!!!",
   "                              x!!!!!!xx              x=====x!!!!!!!!!!!!!!!!!!!!",
   "                              x!!!!!xx               x!!!!!x!!!!!!!!!!!!!!!!!!!!",
   "                              xxxxxxx                xxxxxxx!!!!!!!!!!!!!!!!!!!!",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "               x  x  x                                                                                            ",
   "               xxxxxxx                                                                                            ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                  y                                                                                               ",
   "               x xxx x                                                                                            ",
   "              xx     xx                                                                                           ",
   "             xx |   | xx      xxx   xxx                                                                           ",
   "     @       xxxxxxxxxxx========x   x=============================================================================",
   "    xxx      xxxx   xxxx!!!!!!!!x   x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "    x x      x  x   x  x!!!!!!!xx y xxxxxxxxxxxxxxvxxxxxxxxxxxxxxxxxxxxxvxxxxxxxxxxxxxxxvxxxxxxxvxxxxxxxxxxxxx!!!!",
   "====x x======x x     x x!!!!!!xx                                                                             xx!!!",
   "!!!!x x!!!!!!xx       xx!!!!!xx                                                                               xxx!",
   "!!!!x x!!!!!!x         x!!!!!x    y                                                                             xx",
   "!!!!x x!!!!!!x         x!!!!!x                    y                     y               y       y                 ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   y  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx                                                xx     ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!xx                                                  xxxxxx"],
  ["!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "   xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "     xxxxxvxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                   xx                                                                                         ",
   " @               xx                                                                                           ",
   "xxxx           xx                                                                                             ",
   "!!xxxx       xx                                                                                               ",
   "!!!!xxxx     x                                                                                                ",
   "!!!!!!!x     x                                                                                                ",
   "!!!!!!!x  y  x                                                                                                ",
   "!!!!!!!x     x                                                                                                ",
   "!!!!!!!xx    x                                                                                                ",
   "!!!!!!!x     x                                                                                                ",
   "!!!!!!!x     x                                                                                                ",
   "!!!!!!!x     x                                                                                                ",
   "!!!!!!!x    xx                                                                                                ",
   "!!!!!!!x     x                                                                                                ",
   "!!!!!!!x     x                                                                                                ",
   "!!!!!!!x  y  x                                                             x!!!x                              ",
   "!!!!!!!xx    x                                                              xxx                               ",
   "!!!!!!!x     x                                                                                                ",
   "!!!!!!!x     x                                                    xxx                                         ",
   "!!!!!!!x     x                                                   x!!!x                                        ",
   "!!!!!!!x    xx                                                    xxx        xxx                              ",
   "!!!!!!!x     x                       xxxxxxxxxxxxxxxxxx                     x!!!x                             ",
   "!!!!!!!x     x                        x   x           x                      xxx        xxx                   ",
   "!!!!!!!x  y  x                        x   x           x              x                 x!!!x                  ",
   "!!!!!!!xx    x                xxxxxxxxxxxxxxx     y y  x!!!!!!!!!!!!!!x                 xxx                   ",
   "!!!!!!!x     x               x xxx     xxx x          x!!!!!!!!!!!!!!x                                        ",
   "!!!!!!!x     x               x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "!!!!!!!x     xxxxxxxxxxxxxxxxx            xx                                         xxx                      ",
   "!!xxxxxx    xx                x     y     x                                         x!!!x                xxx  ",
   "!!x x                         x    xxx    x y                                        xxx                 x x  ",
   "!!x                           x    xxx    xxxxxxx      y      y          xxxxx                             x  ",
   "!!x      x                    xy          x      xxx  xxx  xxx  xxx      x   x                             x  ",
   "!!x                           xx          x      x|x  x|x  x|x  x|x        x x x                           x  ",
   "!!x                                       xxxxxxxx xxxx xxxx xxxx xxxx   xxx xxx                           x  ",
   "!!x        x       xxx             y y                                   x         xxx                     x  ",
   "!!x               xxxxx                                                 xxx       x!!!x          x         x  ",
   "!!x               yxxxy            xxx                                  x x        xxx          xxx        x  ",
   "!!x                xxx        xxxxxxxxxxxxx  x yy   yy   yy        yy  xx xx                    xxx        x  ",
   "!!x                 x         x           x  x    x    x    x    x    xx   xx                    x         x  ",
   "!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
